%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                            %
%%  University of Kaiserslautern, Institute of Communications Engineering     %
%%  Copyright (C) 2005 Torsten Schorr                                         %
%%                                                                            %
%%  Author(s)    : Torsten Schorr (schorr@eit.uni-kl.de)                      %
%%  Project start: 20.04.2005                                                 %
%%  Last change  : 02.05.2005                                                 %
%%                                                                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                            %
%%  This program is free software; you can redistribute it and/or modify      %
%%  it under the terms of the GNU General Public License as published by      %
%%  the Free Software Foundation; either version 2 of the License, or         %
%%  (at your option) any later version.                                       %
%%                                                                            %
%%  This program is distributed in the hope that it will be useful,           %
%%  but WITHOUT ANY WARRANTY; without even the implied warranty of            %
%%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             %
%%  GNU General Public License for more details.                              %
%%                                                                            %
%%  You should have received a copy of the GNU General Public License         %
%%  along with this program; if not, write to the Free Software               %
%%  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA %
%%                                                                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                            %
%%  show_signal_info.m                                                        %
%%                                                                            %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function result = show_signal_info( varargin )
% (-1) close figure and reset figure properties, result should be zero
% (0) close figure, result should be zero
% (1) create empty figure without data if not allready open, result==handle to figure
% (2, ...) update/create figure with data in the following arguments, result==handle to figure
%
% (10) put window into foreground
% (11) put window into background
% (12) put minimize figure
% (13, [xpos,ypos,xwidth,ywidth]) == set position of actual window or of position window will have if created
% (14) get position of actual window or last opened window, empty if not available


% Number    Meaning
% 1         DRM mode
% 2         Bandwidth
% 3         interleaver size
% 4         SDC mode 
% 5         MSC mode
% 6         protection levels
% 7         services
% 8         time and date
% 10        input rms
% 11        frequency offset
% 12        sampling rate offset
% 13        FAC MER
% 14        FAC WMER
% 15        MSC MER
% 16        MSC WMER
% 17        MSC CRC
% 18        SDC CRC
% 19        FAC CRC
% 20        frame sync
% 21        time sync
% 23        Service 1: label and type
% 25        Service 1: text message
% 26        Service 2: label and type
% 28        Service 2: text message
% 29        Service 3: label and type
% 31        Service 3: text message
% 32        Service 4: label and type
% 34        Service 4: text message
% 47        running
% 55        play buffer
% 56        audio frame error rate


persistent position_this_figure ...		%position of figure
   hnd_this_figure ...
   is_in_use ...
   ...
   ...	%----------change from here------------------------------
   text_handles value_handles value_strings colors time_and_date_old rms_bars frame_no warn_low_level blink_on;
   settings_number = 20;
   
   
   num_of_items = 56;
   
   num_of_frames = 8;
   
   rms_max = 0.5;
   rms_total = 12;
   rms_green = 7;
   rms_yellow = 3;
   
   bg_color = [0.8 0.8 0.8]; 
   frame_color = [0.7 0.7 0.7];  
   value_fontweight = 'bold';
   services_value_fontweight = 'bold';
   text_font_weight = 'normal';
   
   %------------dont change begin ------------
TAG_NAME = mfilename;
FIGURE_PROCEDURE_NAME = mfilename;

result=-1;
%avoid reentrance 
if ( ~isempty(is_in_use) )
   return; %ignore this call
end

is_in_use = varargin{1};

if( isempty(hnd_this_figure) )
   delete(findobj('Tag', TAG_NAME));
   
end

if( isempty(position_this_figure) )
   myScreenSize = get(0,'ScreenSize');
   position_this_figure = [10, myScreenSize(4) - 340, 450, 300];
end

if( isempty(value_strings) )
    value_strings = cell(1,num_of_items);
    colors = cell(1,num_of_items);
    [colors{:}] = deal(bg_color);
    rms_bars = 0;
    frame_no = -1;
    warn_low_level = 0;
    blink_on = 0;
end


switch varargin{1}
    
    
case 2,
    
    
    update = 1;
    
    switch varargin{2}
        
        case 1, 
            value_string = varargin{3};
        case 2,
            value_string = sprintf('%i kHz',varargin{3});
        case 3,
            if (varargin{3} == 0), value_string = '2.0 s (long)'; else value_string = '400 ms (short)'; end
        case {4,5}
            value_string = varargin{3};
        case 6,
            plevels = varargin{3};
            if (plevels(1) < 0) value_string = sprintf('-/%i (EEP)',plevels(2)); else value_string = sprintf('%i/%i (UEP)',plevels(1),plevels(2)); end
        case 7,
            services = varargin{3};
            value_string = sprintf('%i Audio, %i Data',services(1),services(2));
        case 8,
            time_and_date = varargin{3};
            if (~isequal(time_and_date_old, time_and_date))
                if (time_and_date.day > 0)
                    value_string = sprintf('%02d:%02d %02d-%02d-%02d\n', time_and_date.hours, time_and_date.minutes, mod(time_and_date.year,100), time_and_date.month, time_and_date.day);
                else
                    value_string = '---';
                end
            else
                update = 0;
            end
            
            time_and_date_old = time_and_date;
            
        case 10,
            
            if (varargin{3} == 0 || isnan(varargin{3}))
                new_rms_bars = 0;
            else
                new_rms_bars = floor(log(varargin{3}*5000) / log(rms_max * 5000) * rms_total);
            end
            if (new_rms_bars > rms_total) new_rms_bars = rms_total; end
            if (new_rms_bars < 0) new_rms_bars = 0; end
            
        case 11,
            if (isnan(varargin{3}))
                value_string = '---';
            elseif (abs(varargin{3}) < 1000)
                value_string = sprintf('%0.1f Hz',varargin{3});
            else
                value_string = sprintf('%0.3f kHz',varargin{3}/1000);
            end
        case 12,
            if (isnan(varargin{3}))
                value_string = '---';
            else
                value_string = sprintf('%.0f ppm',varargin{3});
            end
        case {13,14,15,16}
            if (isnan(varargin{3}))
                value_string = '---';
            else                
                value_string = sprintf('%3.1f dB',varargin{3});
            end
        case {17,18,19,20,21,55}
            if (varargin{3} == 0) color = bg_color; elseif (varargin{3} == 1) color = [0 1 0]; elseif(varargin{3} == 2) color = [1 0 0]; elseif(varargin{3} == 3) color = [1 1 0]; end             
        case {23,25,26,28,29,31,32,34}
            value_string = varargin{3};
        case 56,
            if (isnan(varargin{3}))
                value_string = '---';
            else
                value_string = sprintf('%3.1f %%',varargin{3}*100);
            end
    end
    
    if (update == 1)
        switch varargin{2}
            
            case {1,2,3,4,5,6,7,8,11,12,13,14,15,16,56}
                value_strings{varargin{2}} = value_string;
                if(~isempty(hnd_this_figure))
                    set(value_handles(varargin{2}),'String',value_string);
                end
                
            case {17,18,19,20,21,55}
                colors{varargin{2}} = color;
                if(~isempty(hnd_this_figure))
                    set(value_handles(varargin{2}),'BackgroundColor',color);
                end  
                
            case {23,25,26,28,29,31,32,34}
                
                value_strings{varargin{2}} = value_string;
                if(~isempty(hnd_this_figure))
                    set(value_handles(varargin{2}),'String',value_string);
                    set(value_handles(varargin{2}),'TooltipString',value_string);
                end
                
            case 10
                
                if (varargin{3} < 1/5000)
                    warn_low_level = 1;
                    if (blink_on)
                        [colors{35 + new_rms_bars:35 + rms_total - 1}] = deal(bg_color);
                        if(~isempty(hnd_this_figure))
                            set(value_handles(35 + new_rms_bars:35 + rms_total - 1),'BackgroundColor',bg_color);
                        end
                    else
                        [colors{35 + new_rms_bars:35 + rms_total - 1}] = deal([1 0 0]);
                        if(~isempty(hnd_this_figure))
                            set(value_handles(35 + new_rms_bars:35 + rms_total - 1),'BackgroundColor',[1 0 0]);
                        end
                    end
                    
                elseif (warn_low_level)
                    warn_low_level = 0;
                    [colors{35 + new_rms_bars:35 + rms_total - 1}] = deal(bg_color);
                    if(~isempty(hnd_this_figure))
                        set(value_handles(35 + new_rms_bars:35 + rms_total - 1),'BackgroundColor',bg_color);
                    end
                    rms_bars = 0;
                end
                
                blink_on = 1 - blink_on;
                
                if (new_rms_bars < rms_bars)
                        [colors{35 + new_rms_bars:35 + rms_total - 1}] = deal(bg_color);
                        if(~isempty(hnd_this_figure))
                            set(value_handles(35 + new_rms_bars:35 + rms_total - 1),'BackgroundColor',bg_color);
                        end
                        rms_bars = new_rms_bars;
                elseif (new_rms_bars > rms_bars)
                        [colors{35:35 + min(rms_green, new_rms_bars) - 1}] = deal([0 1 0]);
                        if(~isempty(hnd_this_figure))
                            set(value_handles(35:35 + min(rms_green, new_rms_bars) - 1),'BackgroundColor',[0 1 0]);
                        end
                        if (new_rms_bars > rms_green)
                            [colors{35 + rms_green:35 + min(rms_green + rms_yellow, new_rms_bars) - 1}]= deal([1 1 0]);
                            if(~isempty(hnd_this_figure))
                                set(value_handles(35 + rms_green:35 + min(rms_green + rms_yellow, new_rms_bars) - 1),'BackgroundColor',[1 1 0]);
                            end
                        end
                        if (new_rms_bars > rms_green + rms_yellow)
                            [colors{35 + rms_green + rms_yellow:35 + new_rms_bars - 1}] = deal([1 0 0]);
                            if(~isempty(hnd_this_figure))
                                set(value_handles(35 + rms_green + rms_yellow:35 + new_rms_bars - 1),'BackgroundColor',[1 0 0]);
                            end
                        end
                        
                        rms_bars = new_rms_bars;
                end
                
            case 47
                if (frame_no >= 0)
                    if(~isempty(hnd_this_figure))
                        set(value_handles(47 + frame_no),'BackgroundColor',bg_color);
                    end
                end
                if (varargin{3} < 0)
                    frame_no = -1;
                else
                    frame_no = mod(frame_no + 1, num_of_frames);
                    if(~isempty(hnd_this_figure))
                        set(value_handles(47 + frame_no),'BackgroundColor',[0 0.2 1]);
                    end
                end            
        end
    end
    
    result = hnd_this_figure;
   
case -1,
   if ( ~isempty(hnd_this_figure) )
      delete( hnd_this_figure );
      settings_handler(7,settings_number,0);
      position_this_figure = [];
      hnd_this_figure = [];
   end
   hnd_this_axes = [];
   call_count = 0;
   result = 0;
   
case 0,
   if ( ~isempty(hnd_this_figure) )
      position_this_figure = get( hnd_this_figure, 'Position' );
      delete( hnd_this_figure );
      settings_handler(7,settings_number,0);
      hnd_this_figure = [];
   end
   hnd_this_axes = [];
   call_count = 0;
   result = 0;
   
case 1,
    %do we have a figure to plot?
    if ( isempty(hnd_this_figure) )
        hnd_this_figure = figure('Tag', TAG_NAME, ...
            'Position', position_this_figure, ...
            'CloseRequestFcn', [FIGURE_PROCEDURE_NAME,'(0);'], ...
            'Name', 'Signal Information', ...
            'NumberTitle','off', ...
            'MenuBar','none', ...
        	'Resize','off', ...
            'Color',bg_color);
        result = hnd_this_figure;
      settings_handler(7,settings_number,1);
        
        fac_sdc_text_align = 0.01;
        fac_sdc_text_length = 0.2;
        fac_sdc_text_height = 0.06;
        fac_sdc_text_first = 0.915;
        
        signal_text_align = 0.45;
        signal_text_length = 0.2;
        signal_text_height = 0.06;
        signal_text_first = 0.915;
        
        crc_etc_text_align = 0.80;
        crc_etc_text_length = 0.15;
        crc_etc_text_height = 0.06;
        crc_etc_text_first = 0.915;   
        
        fac_sdc_value_align = 0.22;
        fac_sdc_value_length = 0.2;
        fac_sdc_value_height = 0.06;
        fac_sdc_value_first = 0.915;
        
        signal_value_align = 0.64;
        signal_value_length = 0.14;
        signal_value_height = 0.06;
        signal_value_first = 0.915;
        
        crc_etc_value_align = 0.955;
        crc_etc_value_length = 0.03;
        crc_etc_value_height = 0.05;
        crc_etc_value_distance = 0.06;
        crc_etc_value_first = 0.925;   
        
        services_text_align = 0.01;
        services_text_length = 0.2;
        services_text_height = 0.05;
        services_text_distance = 0.10;
        services_text_first = 0.36;
        
        services_value_align = 0.05;
        services_value_align2 = 0.6;
        services_value_length = 0.94;
        services_value_length2 = 0.4;
        services_value_length3 = 0.98;        
        services_value_height = 0.05;
        services_value_distance = 0.05;
        services_value_first = 0.36;
        
        rms_value_align = signal_value_align;
        rms_value_length = 0.01;
        rms_value_xdistance = 0.011;
        rms_value_height = 0.04;
        rms_value_first = 0.93;

        run_value_align = crc_etc_text_align;
        run_value_length = 0.02;
        run_value_xdistance = 0.023;
        run_value_height = 0.04;
        run_value_first = 0.93;
        
        h1 = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'ForegroundColor',[0.6 0.6 0.6], ...
            'ListboxTop',0, ...
            'Position',[0 0.48 0.43 0.51], ...
            'String','FAC/SDC data', ...
            'Style','frame', ...
            'TooltipString','FAC/SDC data');
        h1 = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'ForegroundColor',[0.6 0.6 0.6], ...
            'ListboxTop',0, ...
            'Position',[0.435 0.48 0.35 0.51], ...
            'String','Signal', ...
            'Style','frame', ...
            'Tag','input_frame', ...
            'TooltipString','Signal');        
        h1 = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'ForegroundColor',[0.6 0.6 0.6], ...
            'ListboxTop',0, ...
            'Position',[0.79 0.48 0.21 0.51], ...
            'String','Signal', ...
            'Style','frame', ...
            'Tag','input_frame', ...
            'TooltipString','Signal'); 
        h1 = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'ForegroundColor',[0.6 0.6 0.6], ...
            'ListboxTop',0, ...
            'Position',[0.0 0.0 1 0.47], ...
            'String','Signal', ...
            'Style','frame', ...
            'Tag','input_frame', ...
            'TooltipString','Signal'); 
        
        text_handles(1) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first fac_sdc_text_length fac_sdc_text_height], ...
            'String','DRM Mode:', ...
            'Style','text');
        text_handles(2) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 1 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','Bandwidth:', ...
            'Style','text');
        text_handles(3) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 2 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','Interleaver size:', ...
            'Style','text');
        text_handles(4) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 3 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','SDC mode:', ...
            'Style','text');
        text_handles(5) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 4 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','MSC mode:', ...
            'Style','text');
        text_handles(6) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 5 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','Prot. levels A/B:', ...
            'TooltipString','Protection levels. Unequal Error Protection: A/B; Equal Error Protection: -/B', ...
            'Style','text');
        text_handles(7) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 6 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','Services:', ...
            'Style','text');
        text_handles(8) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_text_align fac_sdc_text_first - 7 * fac_sdc_text_height fac_sdc_text_length fac_sdc_text_height], ...
            'String','Time and Date:', ...
            'TooltipString','Time: UTC; Date: YY-MM-DD', ...
            'Style','text');
        
%         text_handles(9) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',bg_color, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',text_font_weight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[signal_text_align signal_text_first signal_text_length signal_text_height], ...
%             'String','Input mean:', ...
%             'Style','text');
        text_handles(10) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 0 * signal_text_height signal_text_length signal_text_height], ...
            'String','Input level:', ...
            'TooltipString','Input level', ...
            'Style','text');    
        text_handles(11) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 1 * signal_text_height signal_text_length signal_text_height], ...
            'String','Freq. offset:', ...
            'TooltipString','Frequency offset: DC carrier - 12 kHz', ...
            'Style','text');
        text_handles(12) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 2 * signal_text_height signal_text_length signal_text_height], ...
            'String','Smp.rate offs.:', ...
            'TooltipString','Sampling rate offset: (f_clk_transmitter/f_clk_receiver - 1) * 1e6', ...
            'Style','text');
        text_handles(13) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 3 * signal_text_height signal_text_length signal_text_height], ...
            'String','FAC MER:', ...
            'TooltipString','FAC Modulation Error Ratio', ...
            'Style','text');
        text_handles(14) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 4 * signal_text_height signal_text_length signal_text_height], ...
            'String','FAC WMER:', ...
            'TooltipString','FAC Weighted Modulation Error Ratio', ...
            'Style','text');
        text_handles(15) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 5 * signal_text_height signal_text_length signal_text_height], ...
            'String','MSC MER:', ...
            'TooltipString','MSC Modulation Error Ratio', ...
            'Style','text');
        text_handles(16) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 6 * signal_text_height signal_text_length signal_text_height], ...
            'String','MSC WMER:', ...
            'TooltipString','MSC Weighted Modulation Error Ratio', ...
            'Style','text');
        
        text_handles(17) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 1 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','MSC CRC:', ...
            'TooltipString','green: all CRC OK; yellow: some CRC OK; red: no CRC OK', ...
            'Style','text');
        text_handles(18) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 2 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','SDC CRC:', ...
            'TooltipString','green: SDC CRC OK; red: SDC CRC failed', ...
            'Style','text');
        text_handles(19) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 3 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','FAC CRC:', ...
            'TooltipString','green: FAC CRC OK; red: FAC CRC failed', ...
            'Style','text');
        text_handles(20) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 4 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','Frame sync:', ...
            'TooltipString','Frame synchronisation', ...
            'Style','text');
        text_handles(21) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 5 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','Time sync:', ...
            'TooltipString','Time synchronisation', ...
            'Style','text');
        
        text_handles(22) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'ForegroundColor',[0.6 0.6 0.6], ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[0.01 0.4 0.2 0.06], ...
            'String','Services:', ...
            'Style','text');
        
        text_handles(23) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_text_align services_text_first services_text_length services_text_height], ...
            'String','1:', ...
            'Style','text');
        text_handles(26) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_text_align services_text_first - 1 * services_text_distance services_text_length services_text_height], ...
            'String','2:', ...
            'Style','text');
        text_handles(29) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_text_align services_text_first - 2 * services_text_distance services_text_length services_text_height], ...
            'String','3:', ...
            'Style','text');
        text_handles(32) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_text_align services_text_first - 3 * services_text_distance services_text_length services_text_height], ...
            'String','4:', ...
            'Style','text');
        
        text_handles(47) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 6 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','Frames:', ...
            'Style','text');     
        
        text_handles(55) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[crc_etc_text_align crc_etc_text_first - 0 * crc_etc_text_height crc_etc_text_length crc_etc_text_height], ...
            'String','Play buffer:', ...
            'TooltipString','green: filled play buffer; yellow: low play buffer; red: empty play buffer', ...
            'Style','text');
        
        text_handles(56) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',text_font_weight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_text_align signal_text_first - 7 * signal_text_height signal_text_length signal_text_height], ...
            'String','Audio FER:', ...
            'TooltipString','Audio Frame Error Rate', ...
            'Style','text');
        
        disp(value_strings{1})
        value_handles(1) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{1}, ...
            'Style','text');
        value_handles(2) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 1 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{2}, ...
            'Style','text');
        value_handles(3) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 2 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{3}, ...
            'Style','text');
        value_handles(4) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 3 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{4}, ...
            'Style','text');
        value_handles(5) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 4 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{5}, ...
            'Style','text');
        value_handles(6) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 5 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{6}, ...
            'Style','text');
        value_handles(7) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 6 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{7}, ...
            'Style','text');
        value_handles(8) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[fac_sdc_value_align fac_sdc_value_first - 7 * fac_sdc_value_height fac_sdc_value_length fac_sdc_value_height], ...
            'String',value_strings{8}, ...
            'Style','text');
        
%         value_handles(9) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',bg_color, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[signal_value_align signal_value_first signal_value_length signal_value_height], ...
%             'String',value_strings{9}, ...
%             'Style','text');
%         value_handles(10) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',bg_color, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[signal_value_align signal_value_first - 1 * signal_value_height signal_value_length signal_value_height], ...
%             'String',value_strings{10}, ...
%             'Style','text');    
        value_handles(11) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 1 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{11}, ...
            'Style','text');
        value_handles(12) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 2 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{12}, ...
            'Style','text');
        value_handles(13) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 3 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{13}, ...
            'Style','text');
        value_handles(14) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 4 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{14}, ...
            'Style','text');
        value_handles(15) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 5 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{15}, ...
            'Style','text');
        value_handles(16) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 6 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{16}, ...
            'Style','text');
        
        value_handles(17) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{17}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 1 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        value_handles(18) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{18}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 2 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        value_handles(19) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{19}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 3 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        value_handles(20) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{20}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 4 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        value_handles(21) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{21}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 5 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        
        value_handles(23) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{23}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first services_value_length services_value_height], ...
            'String',value_strings{23}, ...
            'Style','text');
%         value_handles(24) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',colors{24}, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',services_value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[services_value_align2 services_value_first  services_value_length services_value_height], ...
%             'String','SWR >>DasDing<<',...%value_strings{24}, ...
%             'Style','text');
        value_handles(25) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{25}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 1 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{25}, ...
            'Style','text');
        value_handles(26) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{26}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 2 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{26}, ...
            'Style','text');
%         value_handles(27) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',colors{27}, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',services_value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[services_value_align2 services_value_first - 2 * services_value_distance services_value_length services_value_height], ...
%             'String',value_strings{27}, ...
%             'Style','text');
        value_handles(28) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{28}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 3 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{28}, ...
            'Style','text');
        value_handles(29) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{29}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 4 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{29}, ...
            'Style','text');
%         value_handles(30) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',colors{30}, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',services_value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[services_value_align2 services_value_first - 4 * services_value_distance services_value_length services_value_height], ...
%             'String',value_strings{30}, ...
%             'Style','text');
        value_handles(31) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{31}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 5 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{31}, ...
            'Style','text');
        value_handles(32) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{32}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 6 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{32}, ...
            'Style','text');
%         value_handles(33) = uicontrol('Parent',hnd_this_figure, ...
%             'Units','normalized', ...
%             'BackgroundColor',colors{33}, ...
%             'FontName','Helvetica', ...
%             'FontSize',9, ...
%             'FontWeight',services_value_fontweight, ...
%             'HorizontalAlignment','left', ...
%             'Position',[services_value_align2 services_value_first - 6 * services_value_distance services_value_length services_value_height], ...
%             'String',value_strings{33}, ...
%             'Style','text');
        value_handles(34) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{34}, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',services_value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[services_value_align services_value_first - 7 * services_value_distance services_value_length services_value_height], ...
            'String',value_strings{34}, ...
            'Style','text');  

% rms bar graph        
        value_handles(35) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{35}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame'); 
        value_handles(36) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{36}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 1 * rms_value_xdistance  rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(37) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{37}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 2 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(38) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{38}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 3 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(39) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{39}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 4 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(40) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{40}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 5 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame'); 
        value_handles(41) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{41}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 6 * rms_value_xdistance  rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(42) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{42}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 7 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(43) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{43}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 8 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(44) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{44}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 9 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');        
        value_handles(45) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{45}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 10 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame');
        value_handles(46) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{46}, ...
            'ForegroundColor',frame_color, ...
            'Position',[rms_value_align + 11 * rms_value_xdistance rms_value_first - 0 * rms_value_height rms_value_length rms_value_height], ...
            'Style','frame'); 

% running frames:
        value_handles(47) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{47}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 0 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(48) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{48}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 1 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(49) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{49}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 2 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(50) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{50}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 3 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(51) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{51}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 4 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(52) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{52}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 5 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(53) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{53}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 6 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');
        value_handles(54) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',colors{54}, ...
            'ForegroundColor',frame_color, ...
            'Position',[run_value_align + 7 * run_value_xdistance run_value_first - 7 * crc_etc_text_height run_value_length run_value_height], ...
            'Style','frame');        
        
        value_handles(55) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'ForegroundColor',frame_color, ...
            'BackgroundColor',colors{55}, ...
            'Position',[crc_etc_value_align crc_etc_value_first - 0 * crc_etc_value_distance crc_etc_value_length crc_etc_value_height], ...
            'Style','frame');
        
        value_handles(56) = uicontrol('Parent',hnd_this_figure, ...
            'Units','normalized', ...
            'BackgroundColor',bg_color, ...
            'FontName','Helvetica', ...
            'FontSize',9, ...
            'FontWeight',value_fontweight, ...
            'HorizontalAlignment','left', ...
            'Position',[signal_value_align signal_value_first - 7 * signal_value_height signal_value_length signal_value_height], ...
            'String',value_strings{56}, ...
            'Style','text');
        
    end
      
end

is_in_use = [];
