######################################################################
# Automatically generated by qmake (3.0) Sun Nov 16 12:53:37 2014
######################################################################

QT +=testlib positioning
TEMPLATE = app
TARGET = t1
INCLUDEPATH += .
DEFINES += HAVE_STDINT_H

HEADERS += ../../src/util-QT/cpos.h \
           ../../src/Parameter.h \
           ../../src/GlobalDefinitions.h
SOURCES += testcpos.cpp ../../src/util-QT/cpos.cpp
