# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded dcp 1.0 [list source [file join $dir dcp.tcl]]
package ifneeded ipio 1.0 [list source [file join $dir ipio.tcl]]
package ifneeded rsciUtil 1.0 [list source [file join $dir rsciUtil.tcl]]
package ifneeded rsci_crc 1.0 [list source [file join $dir rsci_crc.tcl]]
package ifneeded rsci 1.0 [list source [file join $dir rsci.tcl]]
package ifneeded sudp 1.0 [list source [file join $dir sudp.tcl]]
